#-------------------------------------------------------------------------------
# 1. TERMINAL
#-------------------------------------------------------------------------------

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux new-session -A -s main"]


#-------------------------------------------------------------------------------
# 2. WINDOW
#-------------------------------------------------------------------------------

[window]
opacity = 0.9
dimensions = { columns = 120, lines = 40 }
position = { x = 600, y = 350 }
padding = { x = 5, y = 5 }


#-------------------------------------------------------------------------------
# 3. FONT
#-------------------------------------------------------------------------------

[font]
size = 14

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraMono Nerd Font Mono"
style = "Bold"


#-------------------------------------------------------------------------------
# 4. COLORS
#-------------------------------------------------------------------------------

[colors.primary]
background = "#11121D"
foreground = "#a9b1d6"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#a6adc8"

[colors.dim]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"


#-------------------------------------------------------------------------------
# 5. CURSOR
#-------------------------------------------------------------------------------

[cursor]
style = { shape = "Beam" }


#-------------------------------------------------------------------------------
# 6. SELECTION
#-------------------------------------------------------------------------------

[selection]
save_to_clipboard = true


#-------------------------------------------------------------------------------
# 7. KEYBOARD
#-------------------------------------------------------------------------------

[keyboard]
bindings = [
	{ key = "§", chars = "\u0001" },
]
